---
title: "Homework 7"
author: "Adrian Wiegman"
date: "February 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#########################################################################
#FUNCTION: simData
# function to simulate random normal data for a specified experimental setup
#inputs:
#outputs:
#-------------------------------------------------------------------------
simData <- function(nFactors = 1, #number of treatment factors
                    nBlocks = 3, #number of study blocks or sites
                    nTreats = 3, #number of treatment levels for each factor
                    nReps = 10, #number of observations or reps per treatment level per block
                    AVG = 20, #average accross all samples 
                    SD = 5, #standard deviation across all samples
                    fE = 0, #factor effect
                    bE = 0, #block effect
                    tE = 5, #treatment effect
                    rE = 0 #observation number effect important for a time series
                    ){
  ID <- NULL
  factor <- NULL
  block <- NULL
  treatment <- NULL
  observation <- NULL
  response <- NULL
  i <- 0
  for (f in seq(1,nFactors)){
    for (b in seq(1,nBlocks)){
      for (t in seq(1,nTreats)){
        for (r in seq(1,nReps)){
          i <- i + 1
          ID <- c(ID,i)
          factor <- c(factor,f)
          block <- c(block,b)
          treatment <- c(treatment,t)
          observation <- c(observation,r)
          response[i] <- AVG + f*fE* + b*bE + t*tE + r*rE + 5*rnorm(n=1)
        } # end o loop
      } # end t loop
    } # end b loop
  } # end f loop
  Data <- data.frame(ID,
                     factor,
                     block,
                     treatment,
                     observation,
                     response)
  dPlot <- qplot(x=ID,y=response)
  print(dPlot)
  return(Data)
} 
######################################################################

#test function
myData <- simData()
str(myData) 
```

```{r}
# function to conduct Analysis of Variance, produce a vector of outputs and plot a graph
testAOV <- function(x=rep(letters[1:3],each=10), y=runif(30)){
  if (length(y)!=length(x)){
    stop('x and y vectors are not the same lenght')
  }
  response <- y
  treatment <- factor(x) 
  df <- data.frame(ID,response,treatment)
  myAOV  <- aov(response ~ treatment, data=df)
  vAOV <- unlist(myAOV)
  print(summary(myAOV))
  AOVout <- c(p=summary(myAOV)$coefficients[1,5])
  return(AOVout)
}

# function to conduct linear regression and produce a vector of outputs
testREG <- function(x=runif(30), y=runif(30)){
  myREG  <- lm(response ~ treatment, data=myData) # produces results as a list
  vREG <- unlist(myREG) # vectorized regression outputs
  REGout <- c(vREG) # summarized outputs
  return(REGout)
}

```
```{r}
# function to plot a graph with regression data and results
plotAOV <- function(x=rep(letters[1:3],each=10), y=runif(30)){
  # insert control structure to stop the function if treatment is not a factor
  response <- y
  treatment <- factor(x)
  ID = 1:length(x)
  df <- data.frame(treatment,response)
  p <- ggplot(data=df,aes(x=treatment,y=response,fill=factor(treatment))) +
    geom_boxplot()+
    theme_classic()
  return(p)
  }
plotAOV() 
# function to plot a graph with regression data and results
plotREG <- function(data=dataREG, results=REGout){}
```

```{r}
testAOV(y=myData$response,x=myData$treatment)
plotAOV(y=myData$response,x=myData$treatment)
```

